#!/usr/bin/env bash
LC_ALL=C

#
# Pre-commit hook to ensure the branch matches the expected format for the repo
# Adapted from an article by Roland Yeghiazaryan: https://itnext.io/using-git-hooks-to-enforce-branch-naming-policy-ffd81fa01e5e
#

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bug|doc|infrastructure|refactor)\/[0-9]+$"

valid_release_regex="^release\/[0-9]+.[0-9]+.[0-9]+(-(alpha|beta|release).[0-9]+)?$"

message="There is something wrong with your branch name $local_branch.\nBranch names in this project must adhere to this contract: $valid_branch_regex.\nRelease branch names must adhere to this contract: $valid_release_regex.\nYour commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex && ! $local_branch =~ $valid_release_regex ]]
then
    printf "$message\n"
    exit 1
fi

exit 0
