language: cpp

compiler: clang

branches:
  only:
    - master
    - travis-test

before_install:
  - mkdir build
  - cd build
  - cmake ..

install:
  - make
  - chmod +x MidiPianoTestRunner

script:
  - ./MidiPianoTestRunner
