version: 2.1

orbs:
    win: circleci/windows@2.3.0

jobs:
    build:
        executor: win/default
        steps:
            - checkout
            - run:
                name: Installing CMake using Chocolatey
                command: choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=User'
            - run:
                name: Refreshing Powershell
                command: refreshenv
            - run:
                name: Creating build directory
                command: mkdir build
            - run:
                name: Generating build system with CMake
                command: cmake ..
                working_directory: build
            - run:
                name: Building project in Release configuration
                command: cmake --build . --config Release
                working_directory: build
            - persist_to_workspace:
                root: build
                paths:
                    - Release
    test:
        executor: win/default
        steps:
            - attach_workspace:
                at: build
            - run:
                name: Executing Test Runner
                command: ./MidiPianoTestRunner.exe
                working_directory: build/Release
    deploy:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - attach_workspace:
                at: build
            - run:
                name: Tag Release Commit
                command: ./tag-release-commit.py
                working_directory: .circleci
            - run:
                name: Publish Release on GitHub
                command: |
                    VERSION=$(git tag --points-at HEAD)
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./build/Release

workflows:
    version: 2.1
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
            - deploy:
                requires:
                    - test
                filters:
                    branches:
                        only: /release\/(\d+)\.(\d+)\.(\d+)(\/(alpha|beta|rc)(\d+)$|$)/

# Branch Name Valid Values:
# release/MAJOR.MINOR.PATCH					e.g. release/1.0.2
# release/MAJOR.MINOR.PATCH/alphaVERSION	e.g. release/1.0.2/alpha1
# release/MAJOR.MINOR.PATCH/betaVERSION		e.g. release/1.0.2/beta1
# release/MAJOR.MINOR.PATCH/rcVERSION		e.g. release/1.0.2/rc1