version: 2.1

orbs:
    win: circleci/windows@2.3.0

jobs:
    build:
        executor: win/default
        steps:
            - checkout
            - run:
                name: Installing CMake using Chocolatey
                command: choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=User'
            - run:
                name: Refreshing Powershell
                command: refreshenv
            - run:
                name: Listing working directory
                command: pwd
            - run:
                name: Listing current directory
                command: dir
            - run:
                name: Creating build directory
                command: mkdir build
            - run:
                name: Generating build system with CMake
                command: cmake ..
                working_directory: build
            - run:
                name: Building project in Release configuration
                command: cmake --build . --config Release
                working_directory: build
            - persist_to_workspace:
                root: build
                paths:
                    - Release
    test:
        executor: win/default
        steps:
            - attach_workspace:
                at: build
            - run:
                name: Listing working directory
                command: pwd
            - run:
                name: Listing current directory
                command: dir
            - run:
                name: Executing Test Runner
                command: ./Release/MidiPianoTestRunner.exe

workflows:
    version: 2.1
    build_and-test:
        jobs:
            - build
            - test:
                requires:
                    - build