version: 2.1

orbs:
    win: circleci/windows@2.3.0

jobs:
    build:
        executor:
            name: win/default
            size: "medium"
        steps:
            - run: Write-Host "Hello Windows"

workflows:
    version: 2.1
    dist-compile:
        jobs:
            - build