build:
  stage: build
  tags:
    - windows
  script:
    - Write-Host "Installing CMake using Chocolatey"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - Write-Host "Refreshing Powershell"
    - refreshenv
    - Write-Host "$Env:Path"
    - Write-Host "Creating build directory"
    - mkdir build
    - Write-Host "Generating build system with CMake"
    - cd build
    - cmake ..
    - Write-Host "Building project in Release configuration"
    - cmake --build . --config Release
  artifacts:
    paths:
      - build/Release

test:
  stage: test
  tags:
    - windows
  script:
    - Write-Host "Executing Test Runner"
    - cd build/Release
    - ./MidiPianoTestRunner.exe
