build:
  stage: build
  tags:
    - windows
  script: ./.gitlab/scripts/build.ps1
  artifacts:
    paths:
      - build/Release

test:
  stage: test
  tags:
    - windows
  script: ./.gitlab/scripts/test.ps1

deploy:
  stage: deploy
  tags:
    - linux
  rules:
  - if: '$CI_COMMIT_BRANCH =~ /release\/(\d+)\.(\d+)$/'
  script: ./.gitlab/scripts/deploy.sh
