name: Build and Test

on:
  push:
    branches:
    - master
    - 'release/[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ master ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Static code analysis
      uses: deep5050/cppcheck-action@1.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output_file: cppcheck_report.txt
    - name: Upload static analysis report
      uses: actions/upload-artifact@v2
      with:
        name: cppcheck_report.txt
        path: cppcheck_report.txt
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create build directory
      run: mkdir build
    - name: Generate build system
      run: |
        cd build
        cmake ..
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release
    - name: Upload test executable
      uses: actions/upload-artifact@v2
      with:
        name: windows-test-exe
        path: build/Release/MidiPianoTestRunner.exe
    - name: Upload production executable
      uses: actions/upload-artifact@v2
      with:
        name: windows-prod-exe
        path: build/Release/MidiPiano.exe
  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: windows-test-exe
    - name: Run test runner
      run: ./MidiPianoTestRunner.exe
  trigger-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'release/')
    steps:
    - name: Trigger Deploy if on release branch
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Release
        token: ${{ secrets.PERSONAL_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}
