name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create build directory
      run: mkdir build
    - name: Generate build system
      run: |
        cd build
        cmake ..
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release
    - name: Upload test executable
      uses: actions/upload-artifact@v2
      with:
        name: windows-test-exe
        path: build/Release/MidiPianoTestRunner.exe
    - name: Upload production executable
      uses: actions/upload-artifact@v2
      with:
        name: windows-prod-exe
        path: build/Release/MidiPiano.exe
  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: windows-test-exe
    - name: Run test runner
      run: ./MidiPianoTestRunner.exe
  release:
    runs-on: ubuntu-latest
    needs: test
    if: branch
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: windows-prod-exe
    - name: Create a Release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.output_url }}
        asset_path: MidiPiano.exe
        asset_name: midi-piano-${{ github.ref }}.exe
        asset_content_type: application/vnd.microsoft.portable-executable
