name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create build directory
      run: |
        mkdir build
        cd build
    - name: Generate build system
      run: cmake ..
    - name: Build project
      run: cmake --build . --config Release
